---
- name: "Create a VM in local KVM from base image"
  hosts: localhost
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_prompt:

    - name: vmpath
      prompt: "Choose the KVM path to use"
      private: no
      default: "/run/media/alolivei/ALEXON/KVM_VMs"

    - name: image_name
      prompt: "Choose the image to use"
      private: no
      default: "rhel9"

    - name: vmname
      prompt: "Choose the VM name"
      private: no
      default: "teste"

    - name: vmdesc
      prompt: "Choose the VM description"
      private: no
      default: "Teste"

    - name: vmip
      prompt: "Choose the VM IP (192.168.1.x)"
      private: no
      default: "253"

    - name: vmvcpus
      prompt: "(Optional) Choose the amount of vCPUs"
      private: no
      default: "1"

    - name: vmramkb
      prompt: "(Optional) Choose the amount of RAM in KiB"
      private: no
      default: "1048576"

    - name: vmnet
      prompt: "(Optional) Choose the network"
      private: no
      default: "default"

    #- name: vmdiskgb
    #  prompt: "(Optional) Choose the value for the disk resizing in GiB (Default: 10)"
    #  private: no

  tasks:
  
   - name: "KVM/Libvirt/QEMU Provisioning Role"
     include_role:
       name: mylab_deploy
     vars:
       imagename: "{{ image_name }}"
       vm_path: "{{ vmpath }}"
       vm_name: "{{ vmname }}"
       vm_desc: "{{ vmdesc }}"
       vm_vcpus: "{{ vmvcpus }}"
       vm_ram_kb: "{{ vmramkb }}"
       vm_net: "{{ vmnet }}"
       vm_ip: "{{ vmip }}"
       #vm_disk_gb: "{{ vmdiskgb }}"
