---
# tasks file for mylab_deploy
- name: "Get VMs list"
  community.libvirt.virt:
    command: list_vms
  register: all_vms
  changed_when: no

- name: "Create VM if not exists"
  block:
    
    - name: "Remove past access history to duplicated IPs"
      lineinfile:
        path: ~/.ssh/known_hosts
        backrefs: yes
        regexp: "{{ item }}"
        state: absent
      loop:
        - '^192.168.1.253'
        - '^192.168.1.254'
    
    - name: "Clone the base image to a new VM"
      copy:
        dest: "{{ vm_path }}/{{ vm_name }}.qcow2"
        src: "/run/media/alolivei/ALEXON/KVM_VMs/{{ imagename }}.qcow2"
        force: no
      register: copy_results

    - name: "Customizing RHEL 8.6 VM image"
      command: |
        virt-customize -a {{ vm_path }}/{{ vm_name }}.qcow2 \
        --hostname {{ vm_name }}.example.local \
        --run-command 'sed -i 's/192.168.1.253/192.168.1.{{ vm_ip }}/g' /etc/sysconfig/network-scripts/ifcfg-enp1s0' \
        --ssh-inject 'root:file:{{ ssh_key }}' \
        --selinux-relabel
      when: (copy_results is changed) and (imagename == "rhel86")

    - name: "Customizing RHEL 9 VM image"
      command: |
        virt-customize -a {{ vm_path }}/{{ vm_name }}.qcow2 \
        --hostname {{ vm_name }}.example.local \
        --run-command 'sed -i 's/192.168.1.253/192.168.1.{{ vm_ip }}/g' /etc/NetworkManager/system-connections/enp1s0.nmconnection' \
        --ssh-inject 'root:file:{{ ssh_key }}' \
        --selinux-relabel
      when: (copy_results is changed) and (imagename == "rhel9")
    
    - name: "(Optional) Resize the newly VM created disk"
      command: qemu-img resize {{ vm_path }}/{{ vmname }}.qcow2 +{{ vm_disk_gb }}G
      when: vm_disk_gb|length > 0

    - name: "Define a RHEL 8.6 VM"
      community.libvirt.virt:
        command: define
        xml: "{{ lookup('template', 'rhel86-template.xml.j2') }}"
      when: imagename == "rhel86"

    - name: "Define a RHEL 9 VM"
      community.libvirt.virt:
        command: define
        xml: "{{ lookup('template', 'rhel9-template.xml.j2') }}"
      when: imagename == "rhel9"

    - name: "Change the VM title to the same as name"
      command: virsh desc --domain {{ vm_name }} --config --title {{ vm_name }}

    - name: "Change the VM description"
      command: virsh desc --domain {{ vm_name }} --config --new-desc "{{ vm_desc }}"
  when: "vm_name not in all_vms.list_vms"

- name: "Start the newly created VM"
  community.libvirt.virt:
    name: "{{ vm_name }}"
    state: running
  register: vm_start_results
  until: "vm_start_results is success"
  retries: 3
  delay: 2
